set_location_assignment PIN_AA25 -to write_wrusedw_seg1[6]
set_location_assignment PIN_AA26 -to write_wrusedw_seg1[5]
set_location_assignment PIN_AB26 -to write_wrusedw_seg1[4]
set_location_assignment PIN_AB27 -to write_wrusedw_seg1[3]
set_location_assignment PIN_Y27 -to write_wrusedw_seg1[2]
set_location_assignment PIN_AA28 -to write_wrusedw_seg1[1]
set_location_assignment PIN_V25 -to write_wrusedw_seg1[0]

set_location_assignment PIN_W25 -to write_wrusedw_seg0[6]
set_location_assignment PIN_V23 -to write_wrusedw_seg0[5]
set_location_assignment PIN_W24 -to write_wrusedw_seg0[4]
set_location_assignment PIN_W22 -to write_wrusedw_seg0[3]
set_location_assignment PIN_Y24 -to write_wrusedw_seg0[2]
set_location_assignment PIN_Y23 -to write_wrusedw_seg0[1]
set_location_assignment PIN_AA24 -to write_wrusedw_seg0[0]

set_location_assignment PIN_AB22 -to read_wrusedw_seg3[6]
set_location_assignment PIN_AB25 -to read_wrusedw_seg3[5]
set_location_assignment PIN_AB28 -to read_wrusedw_seg3[4]
set_location_assignment PIN_AC25 -to read_wrusedw_seg3[3]
set_location_assignment PIN_AD25 -to read_wrusedw_seg3[2]
set_location_assignment PIN_AC27 -to read_wrusedw_seg3[1]
set_location_assignment PIN_AD26 -to read_wrusedw_seg3[0]

set_location_assignment PIN_AC30 -to read_wrusedw_seg2[6]
set_location_assignment PIN_AC29 -to read_wrusedw_seg2[5]
set_location_assignment PIN_AD30 -to read_wrusedw_seg2[4]
set_location_assignment PIN_AC28 -to read_wrusedw_seg2[3]
set_location_assignment PIN_AD29 -to read_wrusedw_seg2[2]
set_location_assignment PIN_AE29 -to read_wrusedw_seg2[1]
set_location_assignment PIN_AB23 -to read_wrusedw_seg2[0]

set_location_assignment PIN_AD27 -to read_wrusedw_seg1[6]
set_location_assignment PIN_AF30 -to read_wrusedw_seg1[5]
set_location_assignment PIN_AF29 -to read_wrusedw_seg1[4]
set_location_assignment PIN_AG30 -to read_wrusedw_seg1[3]
set_location_assignment PIN_AH30 -to read_wrusedw_seg1[2]
set_location_assignment PIN_AH29 -to read_wrusedw_seg1[1]
set_location_assignment PIN_AJ29 -to read_wrusedw_seg1[0]

set_location_assignment PIN_AH28 -to read_wrusedw_seg0[6]
set_location_assignment PIN_AG28 -to read_wrusedw_seg0[5]
set_location_assignment PIN_AF28 -to read_wrusedw_seg0[4]
set_location_assignment PIN_AG27 -to read_wrusedw_seg0[3]
set_location_assignment PIN_AE28 -to read_wrusedw_seg0[2]
set_location_assignment PIN_AE27 -to read_wrusedw_seg0[1]
set_location_assignment PIN_AE26 -to read_wrusedw_seg0[0]